name:                aoc2021
version:             0.1.0.0
github:              "cassaundra/aoc2021"
license:             BSD3
author:              "Cassaundra Smith"
maintainer:          "cass@cassaundra.io"
copyright:           "2021 Cassaundra Smith"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cassaundra/aoc2021#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- megaparsec
- text

library:
  source-dirs: src

executables:
  aoc2021-day01-part1:
    main: app/Day01/Part1.hs
    ghc-options:
    - -main-is Day01.Part1.main
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2021

  aoc2021-day01-part2:
    main: app/Day01/Part2.hs
    ghc-options:
    - -main-is Day01.Part2.main
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2021

  aoc2021-day02-part1:
    main: app/Day02/Part1.hs
    ghc-options:
    - -main-is Day02.Part1.main
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2021
    - lens
    - megaparsec
    - text

tests:
  day01-test:
    main: Day01Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2021
    - hspec
